### ISSUE TITLE
Support cordova-cli 9.0.0 - requireCordovaModule deprecation

### ISSUE THREAD

**Issue by tombell** [GEDYSIntraWare/cordova-plugin-call-directory#13]
The use of `context.requireCordovaModule` for non-cordova dependencies has been removed, and suggests you now add the dependency to the plugins `package.json` and `require`'d normally.

https://github.com/apache/cordova-lib/pull/707

**Comment by NiklasMerz** [comment]
Thanks for reporting. Would you like to do the pull request? Shouldn´t be too many changes.
