### ISSUE TITLE
[BUG] Error while trying to call reloadExtension()

### ISSUE THREAD

**Issue by heiko-heil** [GEDYSIntraWare/cordova-plugin-call-directory#17]
**Describe the bug**
I receive the following error message after calling reloadExtension:
The operation couldn't be completed. (com.apple.CallKit.error.calldirectory manager error 7.)
Remark: The EXTENSION and GROUP references are correct.

**To Reproduce**
Via ionic-angular 3.9.2:
```
this.callDirectory.reloadExtension()
  .then((res: string) => {
  console.log(res);
  })
  .catch((error: any) => {
    console.error(error);
  });
```

**Expected behavior**
Reload extension.

**Logs**
<details>
  <pre>The operation couldn't be completed.</pre>
  <pre>(com.apple.CallKit.error.calldirectory manager error 7.)</pre>
</details>

Any hints?

Best regards
Heiko

**Comment by NiklasMerz** [comment]
Have you checked the Xcode project for possible errors? Looks like your error has to do something with loading Check [here](https://developer.apple.com/documentation/callkit/cxerrorcodecalldirectorymanagererror/code/currentlyloading). Are you calling the function app start? Did you wait for platform ready?

[Error documentation](https://developer.apple.com/documentation/callkit/cxerrorcodecalldirectorymanagererror/code)

**Comment by heiko-heil** [comment]
Thank you for your swift reply! Xcode shows no error. Even the initial caller id setup works.
The call takes place in app.component.ts:
```
platform.ready().then(() => {
if (platform.is('cordova')) {
```

**Comment by NiklasMerz** [comment]
Did you try turning the extension on and off in the iOS systems settings? :-) Did you already add data?

**Comment by heiko-heil** [comment]
Yes. After disabling the extension I receive the "extensionDisabled" (6) error (as expected). But after activating I still receive the error number 7.
After the initial setup (via addIdentification(items)) the stored numbers are resolved correctly. But I want to implement the following trigger:
- remove all stored items (via removeAllIdentification())
- add new items
- reload extension

**Comment by NiklasMerz** [comment]
Have you tried reloading after removing and after adding again? Maybe you don't wait long enought / until the promise resolves. There should be some logs on the Xcode console, too. Wait for success signals there.

**Comment by heiko-heil** [comment]
Thank you for your swift replies! I used two subsequent calls (according to the Ionic documentation: https://ionicframework.com/docs/v3/native/call-directory/). That was the mistake!

Now I am calling reloadExtension() within the "then()"-section of the 1st command. Now it seems to work!
