### ISSUE TITLE
[BUG] Cannot install plugin

### ISSUE THREAD

**Issue by DeliveryBMS** [GEDYSIntraWare/cordova-plugin-call-directory#25]
**Describe the bug**
Cannot install plugin.

**To Reproduce**
cordova plugin add cordova-plugin-call-directory --variable EXT_NAME="Cordova-Directory" --variable ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES="NO" --variable DEVELOPMENT_TEAM="TEAMID" --variable PROVISIONING_PROFILE="prov-id-5677-67567567.."

**Expected behavior**
Install the plugin
**Logs**
<details>
  <pre>[Failed to fetch plugin cordova-plugin-call-directory via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
CordovaError: Error: npm: Command failed with exit code 128 Error output:
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/GEDYSIntraWare/cordova-node-xcode.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simone/.npm/_logs/2021-08-02T07_05_31_942Z-debug.log]</pre>
</details>

**Comment by NiklasMerz** [comment]
Thanks for creating the issue. I just merged a fix for this. Until we release a new version on NPM you can install the plugin via git:

`cordova plugin add https://github.com/GEDYIntraWare/cordova-plugin-call-directory --variable EXT_NAME="Cordova-Directory" --variable ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES="NO" --variable DEVELOPMENT_TEAM="TEAMID" --variable PROVISIONING_PROFILE="prov-id-5677-67567567.."`
